-- Some Commands Used for Defining the Database According to the Design

USE buy_shu;

CREATE TABLE CATEGORY (
    CATEGORY_ID int AUTO_INCREMENT PRIMARY KEY,
    TRADER_ID int,
    CATEGORY_TYPE VARCHAR(200),
    FOREIGN KEY (TRADER_ID) REFERENCES TRADER(TRADER_ID)
);

CREATE TABLE TRADER (
    TRADER_ID int AUTO_INCREMENT PRIMARY KEY,
    TRADER_NAME VARCHAR(200),
    TRADER_PASSWORD VARCHAR(200),
    TRADER_EMAIL VARCHAR(200)
);

CREATE TABLE PRODUCT (
    PRODUCT_ID int AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(255),
    PRODUCT_PRICE int,
    PRODUCT_STOCK int,
    PRODUCT_DETAIL VARCHAR(1000),
    ALLERGY_INFORMATION VARCHAR(500),
    UPLOAD VARCHAR(255),
    CATEGORY_ID int,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);

CREATE TABLE CUSTOMER (
    CUSTOMER_ID int AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
	ADDRESS VARCHAR(255),
	PASSWORD VARCHAR(255),
	EMAIL VARCHAR(255)
);

CREATE TABLE CART (
    CART_ID int AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID int,
    PRODUCT_ID int,
	PRODUCT_QUANTITY int,
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)  
);

CREATE TABLE ORDERS (
	ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID INT,
    CUSTOMER_ID INT,
    PAYMENT_ID INT,
    PRODUCT_QUANTITY INT,
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
	FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT(PAYMENT_ID)
);

CREATE TABLE ORDER_DETAIL(
	ORDER_DETAIL_ID INT AUTO_INCREMENT PRIMARY KEY,
    SHIPPING_ADDRESS VARCHAR(255),
    ORDER_AMOUNT INT,
    PAYMENT_ID INT,
    ORDER_STATUS TINYINT(1),
	FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT(PAYMENT_ID)
);

CREATE TABLE PAYMENT(
	PAYMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    PAYMENT_AMOUNT INT
);

-- Some Commands Used During Site Development

SELECT * FROM CUSTOMER;

INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, ADDRESS, PASSWORD, EMAIL)
VALUES ('Anamol', 'Dhakal', 'KTM', 'password123', 'anmol@example.com');

SELECT * FROM TRADER;
SELECT * FROM PRODUCT;
SELECT * FROM CATEGORY;
SELECT * FROM CART;
SELECT * FROM ORDERS;
SELECT * FROM ORDER_DETAIL;

DELETE FROM CUSTOMER
WHERE CUSTOMER_ID = 4;

SELECT TRIGGER_NAME, EVENT_MANIPULATION, EVENT_OBJECT_TABLE, ACTION_TIMING, ACTION_STATEMENT
FROM information_schema.TRIGGERS
WHERE TRIGGER_SCHEMA = 'buy_shu';

ALTER TABLE PRODUCT
CHANGE COLUMN UPLOAD UPLOAD VARCHAR(255);
